#!/bin/bash
FILENAME=$(basename "${1}")
if [ -z ${2} ]; then
  echo "only one Photo given"
  FILENAME2=${FILENAME}
else  
  FILENAME2=$(basename "${2}")
fi  
EXTENSION="${FILENAME##*.}"
FILENAME="${FILENAME%.*}"
FILENAME2="${FILENAME2%.*}"
echo "EXTENSION = ${EXTENSION}"
echo "FILENAME = ${FILENAME}"
echo "FILENAME2= ${FILENAME2}"
magick ${FILENAME}.${EXTENSION} ${FILENAME}.${EXTENSION} ${FILENAME}.${EXTENSION} ${FILENAME}.${EXTENSION} +append ${FILENAME}_4x1.${EXTENSION}
magick ${FILENAME2}.${EXTENSION} ${FILENAME2}.${EXTENSION} ${FILENAME2}.${EXTENSION} ${FILENAME2}.${EXTENSION} +append ${FILENAME2}_4x1.${EXTENSION}
magick ${FILENAME}_4x1.${EXTENSION} ${FILENAME2}_4x1.${EXTENSION} -append ${FILENAME}_4x2.${EXTENSION}
#rm ${FILENAME}_4x1.${EXTENSION}
#rm ${FILENAME2}_4x1.${EXTENSION}

