#!/bin/bash

# User specific environment and startup programs

export GOPATH="${HOME}/work/go"

alias ic="ibmcloud"
alias kc="kubectl"
alias git='LANG=en_US.UTF-8 git'
export CLICOLOR=1
export LSCOLORS=gxfxcxdxbxegedabagaced
#source /usr/local/opt/chruby/share/chruby/chruby.sh
#source /usr/local/opt/chruby/share/chruby/auto.sh
export PATH=$GOPATH/bin:$PATH:/usr/local/sbin

